name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x' # Adjust the version as needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app for release
        run: dotnet build --configuration Release

      - name: Publish build artifacts
        run: dotnet publish --configuration Release --output ./publish
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./publish